### ISSUE TITLE
help pls 

### ISSUE THREAD

**Issue by Lida1606** [BoobBot/Boo#9]
I can't start the bot where can I enter the bot token Traceback (most recent call last):
   File "/home/pi/Desktop/Open/Boo-master/src/boo.py", line 3, in <module>
     import discord
ModuleNotFoundError: No module named 'discord'

**Comment by IamTails** [comment]
It's likely you don't have discord.py installed.

That being said, This hasn't been touched in a long time. I'm not sure what changes have happened to d.py in the meantime and if any of them were breaking.
